version: "1.0"
services:
  angular:
    container_name: angular
    build: ./

    environment:
      - PORT=4000
    networks:
      - backend
  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: nginx
    ports:
      - "81:80"
    networks:
      - backend
    depends_on:
      - angular
networks:
  backend:
    driver: bridge
