version: "1.0"
services:
  angular:
    container_name: angular
    build: ./
    # ports:
    # - "4000:4000"
    environment:
      - PORT=4000
    networks:
      - backend
  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: nginx
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - angular
networks:
  backend:
    driver: bridge
