apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cv-ingress
  namespace: cv-portfolio
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  tls:
    - hosts:
        - balashov-maxim.ru
      secretName: balashov-maxim-tls
  rules:
    - host: cv.balashov-maxim.ru
      http:
        paths:
          # - path: /api/contact
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: cv-contact-me
          #       port:
          #         number: 8090
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cv-backend
                port:
                  number: 3333
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: cv-backend
                port:
                  number: 3333
          - path: /healthz
            pathType: Prefix
            backend:
              service:
                name: cv-backend
                port:
                  number: 3333
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cv-frontend
                port:
                  number: 4000
