/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AboutMeDto as DtoAboutMeDto } from '../../models/dto/about-me-dto';

export interface AboutMeGet$Params {
}

export function aboutMeGet(http: HttpClient, rootUrl: string, params?: AboutMeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DtoAboutMeDto>> {
  const rb = new RequestBuilder(rootUrl, aboutMeGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DtoAboutMeDto>;
    })
  );
}

aboutMeGet.PATH = '/about-me';
