/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TechListResponse as DtoTechListResponse } from '../../models/dto/tech-list-response';

export interface TechGet$Params {

/**
 * Номер страницы
 */
  page?: number;

/**
 * Размер страницы
 */
  size?: number;
}

export function techGet(http: HttpClient, rootUrl: string, params?: TechGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DtoTechListResponse>> {
  const rb = new RequestBuilder(rootUrl, techGet.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DtoTechListResponse>;
    })
  );
}

techGet.PATH = '/tech';
