/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeleteResponse as DtoDeleteResponse } from '../../models/dto/delete-response';

export interface TechDelete$Params {
  
    /**
     * Список ID для удаления
     */
    body: {
} & {
'ids'?: Array<number>;
}
}

export function techDelete(http: HttpClient, rootUrl: string, params: TechDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<DtoDeleteResponse>> {
  const rb = new RequestBuilder(rootUrl, techDelete.PATH, 'delete');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DtoDeleteResponse>;
    })
  );
}

techDelete.PATH = '/tech';
