/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TechnologyDto as DtoTechnologyDto } from '../../models/dto/technology-dto';

export interface TechPut$Params {
  
    /**
     * Данные технологии
     */
    body: {
} & {
'description'?: string;
'id'?: number;
'logoUrl'?: string;
'title'?: string;
}
}

export function techPut(http: HttpClient, rootUrl: string, params: TechPut$Params, context?: HttpContext): Observable<StrictHttpResponse<DtoTechnologyDto>> {
  const rb = new RequestBuilder(rootUrl, techPut.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DtoTechnologyDto>;
    })
  );
}

techPut.PATH = '/tech';
