/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TechnologyWithTagsDto as DtoTechnologyWithTagsDto } from '../../models/dto/technology-with-tags-dto';

export interface TechTechIdGet$Params {

/**
 * ID технологии
 */
  techID: number;
}

export function techTechIdGet(http: HttpClient, rootUrl: string, params: TechTechIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DtoTechnologyWithTagsDto>> {
  const rb = new RequestBuilder(rootUrl, techTechIdGet.PATH, 'get');
  if (params) {
    rb.path('techID', params.techID, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DtoTechnologyWithTagsDto>;
    })
  );
}

techTechIdGet.PATH = '/tech/{techID}';
