/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApiError as ApierrorsApiError } from './models/apierrors/api-error';
export type { AboutMeDto as DtoAboutMeDto } from './models/dto/about-me-dto';
export type { DeleteResponse as DtoDeleteResponse } from './models/dto/delete-response';
export type { EducationDto as DtoEducationDto } from './models/dto/education-dto';
export type { EducationListResponse as DtoEducationListResponse } from './models/dto/education-list-response';
export type { HeroDto as DtoHeroDto } from './models/dto/hero-dto';
export type { TagDto as DtoTagDto } from './models/dto/tag-dto';
export type { TagListResponse as DtoTagListResponse } from './models/dto/tag-list-response';
export type { TechListResponse as DtoTechListResponse } from './models/dto/tech-list-response';
export type { TechnologyDto as DtoTechnologyDto } from './models/dto/technology-dto';
export type { TechnologyWithTagsDto as DtoTechnologyWithTagsDto } from './models/dto/technology-with-tags-dto';
export type { WorkHistoryDto as DtoWorkHistoryDto } from './models/dto/work-history-dto';
export type { WorkHistoryListResponse as DtoWorkHistoryListResponse } from './models/dto/work-history-list-response';
export type { WorkHistoryWithTechnologiesDto as DtoWorkHistoryWithTechnologiesDto } from './models/dto/work-history-with-technologies-dto';
