import { ITechnologyItem } from '../../types/types';

export const TECHNOLOGIES: Record<string, ITechnologyItem> = {
  Typescript: {
    title: 'Typescript',
    id: 'Typescript',
    description:
      'TypeScript делает код понятнее и надёжнее, добавляет статическую типизацию (переменные привязаны к конкретным типам данных) и может быть скомпилирован в JavaScript.',
    tags: ['ProgLang', 'Frontend', 'Backend'],
    logo: null,
  },
  React: {
    title: 'React',
    id: 'React',
    description:
      'Одна из популярных JavaScript-библиотека для создания пользовательских интерфейсов',
    tags: ['Frontend'],
    logo: null,
  },
  Redux: {
    title: 'Redux',
    id: 'Redux',
    description: 'Стейт менеджер веб-приложения',
    tags: ['StateManager'],
    logo: null,
  },
  Next: {
    title: 'Next',
    id: 'Next',
    description:
      'Это основанный на React фреймворк, предназначенный для разработки веб-приложений, обладающих функционалом, выходящим за рамки SPA',
    tags: ['Backend', 'SSR', 'Frontend', 'Frameworks'],
    logo: null,
  },
  Chromatic: {
    title: 'Chromatic',
    id: 'Chromatic',
    description:
      'Инструмент визуального тестирования, который сканирует все возможные состояния пользовательского интерфейса в разных браузерах, чтобы выявить ошибки во внешнем виде и функциональности.',
    tags: ['Testing'],
    logo: null,
  },
  Loki: {
    title: 'Loki',
    id: 'Loki',
    description: 'Инструмент визуального регрессионного тестирования',
    tags: ['Testing'],
    logo: null,
  },
  Docker: {
    title: 'Docker',
    id: 'Docker',
    description: 'Инструмент для контейнеризации',
    tags: ['Devops'],
    logo: null,
  },
  'Gitlab-CI': {
    title: 'Gitlab-CI',
    id: 'Gitlab-CI',
    description: 'Инструмент для автоматизации CI/CD процессов',
    tags: ['Devops'],
    logo: null,
  },
  Webpack: {
    title: 'Webpack',
    id: 'Webpack',
    description: 'Популярный сборщик веб-приложений',
    tags: ['Frontend'],
    logo: null,
  },
  Websocket: {
    title: 'Websocket',
    id: 'Websocket',
    description:
      'Двунаправленный протокол связи, позволяющий обмениваться сообщениями в режиме реального времени',
    tags: ['Frontend', 'Backend'],
    logo: null,
  },
  Storybook: {
    title: 'Storybook',
    id: 'Storybook',
    description:
      'Инструмент для организации пользовательских интерфейсов, который делает процессы разработки компонентов, тестирования и создания документации более эффективными и простыми',
    tags: ['Testing', 'UI'],
    logo: null,
  },
  'Node.js': {
    title: 'Node.js',
    id: 'Node.js',
    description:
      'Среда выполнения кода JavaScript, которая позволяет писать серверный код и скрипты вне браузера',
    tags: ['Backend', 'CodeGeneration'],
    logo: null,
  },
  Bash: {
    title: 'Bash',
    id: 'Bash',
    description: 'Оболочка операционных систем Unix ',
    tags: ['Devops'],
    logo: null,
  },
  Vite: {
    title: 'Vite',
    id: 'Vite',
    description:
      'Быстрый сборщик веб-приложений более легкий в настройке конфигурации чем webpack',
    tags: ['Frontend'],
    logo: null,
  },
  SharedWorker: {
    title: 'SharedWorker',
    id: 'SharedWorker',
    description:
      'Worker, который создает общий контекст выполнения, доступный для нескольких окон, вкладок или фреймов приложения',
    tags: ['Frontend'],
    logo: null,
  },
  BroadcastChannel: {
    title: 'BroadcastChannel',
    id: 'BroadcastChannel',
    description:
      'Канал, на который можно подписаться из любого контекста просмотра данного источника',
    tags: ['Frontend'],
    logo: null,
  },
  JavaScript: {
    title: 'JavaScript',
    id: 'JavaScript',
    description:
      'Мультипарадигменный язык программирования с прототипным наследованием',
    tags: ['ProgLang'],
    logo: null,
  },
  Git: {
    title: 'Git',
    id: 'Git',
    description: 'Система контроля версий',
    tags: [],
    logo: null,
  },
  Bootstrap: {
    title: 'Bootstrap',
    id: 'Bootstrap',
    description: 'Популярный UI фреймворк',
    tags: ['Frontend', 'UI'],
    logo: null,
  },
  Sass: {
    title: 'Sass',
    id: 'Sass',
    description: 'CSS препроцессор',
    tags: ['UI', 'Frontend'],
    logo: null,
  },
  Figma: {
    title: 'Figma',
    id: 'Figma',
    description: 'Создание макетов пользовательский интерфейсов',
    tags: ['UI'],
    logo: null,
  },
  MongoDB: {
    title: 'MongoDB',
    id: 'MongoDB',
    description: 'Документная база данных',
    tags: ['Backend', 'Database'],
    logo: null,
  },
  PostgreSQL: {
    title: 'PostgreSQL',
    id: 'PostgreSQL',
    description: 'Реляционная база данных',
    tags: ['Backend', 'Database'],
    logo: null,
  },
  AntDesign: {
    title: 'AntDesign',
    id: 'AntDesign',
    description: 'UI библиотека',
    tags: ['UI', 'Frontend'],
    logo: null,
  },
  'Express.js': {
    title: 'Express.js',
    id: 'Express.js',
    description: 'Backend фреймворк на node.js',
    tags: ['Backend'],
    logo: null,
  },
  'ISO 7 bit': {
    title: 'ISO 7 bit',
    id: 'ISO 7 bit',
    description:
      'Язык программирования используемый в ЧПУ станках для управления электроавтоматикой',
    tags: ['ProgLang'],
    logo: null,
  },
  'CNC postprocessors': {
    title: 'CNC postprocessors',
    id: 'CNC postprocessors',
    description:
      'Программа используемая для создания кода на языке ISO 7 bit из сода CAM системы',
    tags: ['CodeGeneration'],
    logo: null,
  },
  CAM: {
    title: 'CAM',
    id: 'CAM',
    description: 'Система автоматической подготовки управляющих программ',
    tags: [],
    logo: null,
  },
  CAD: {
    title: 'CAD',
    id: 'CAD',
    description:
      'Система автоматизированного проектирования для создания 3-D моделей и технологической документации',
    tags: [],
    logo: null,
  },
  NGINX: {
    title: 'NGINX',
    id: 'NGINX',
    description: 'Веб-сервер',
    tags: ['Backend', 'Devops'],
    logo: null,
  },
  Python: {
    title: 'Python',
    id: 'Python',
    description:
      'Скриптовый язык программирования, подходит для решения разнообразных задач на разных платформах',
    tags: ['ProgLang'],
    logo: null,
  },
  Django: {
    title: 'Django',
    id: 'Django',
    description: 'Фреймворк Python для создания веб-приложений',
    tags: ['Backend', 'Frameworks'],
    logo: null,
  },
  Nest: {
    title: 'Nest',
    id: 'Nest',
    description:
      'Backend фреймворк на node.js, может использовать в своей основе Express.js',
    tags: ['Backend', 'Frameworks'],
    logo: null,
  },
  MUI: {
    title: 'MUI',
    id: 'MUI',
    description: 'Material UI - популярная React библиотека компонентов',
    tags: ['Frontend', 'UI'],
    logo: null,
  },
  'Chakra UI': {
    title: 'Chakra UI',
    id: 'Chakra UI',
    description: 'UI фреймворк',
    tags: ['Frontend', 'UI'],
    logo: null,
  },
  'Django REST Framework': {
    title: 'Django REST Framework',
    id: 'Django REST Framework',
    description: 'Фреймворк для создания REST на Django',
    tags: ['Backend', 'Frameworks'],
    logo: null,
  },
  Haskell: {
    title: 'Haskell',
    id: 'Haskell',
    description: 'Функциональный язык программирования',
    tags: ['FP', 'ProgLang'],
    logo: null,
  },
  Angular: {
    title: 'Angular',
    id: 'Angular',
    description: 'ООП Фреймворк использующий DI, модульность, декораторы...',
    tags: ['Frameworks', 'Frontend'],
    logo: null,
  },
  'React-hook-form': {
    title: 'React-hook-form',
    id: 'React-hook-form',
    description: 'Библиотека управления формами',
    tags: ['Forms', 'Frontend'],
    logo: null,
  },
  Formik: {
    title: 'Formik',
    id: 'Formik',
    description: 'Библиотека управления формами',
    tags: ['Forms', 'Frontend'],
    logo: null,
  },
  Tailwind: {
    title: 'Tailwind',
    id: 'Tailwind',
    description:
      'UI библиотека для стилизации приложения основанная на селекторах классов',
    tags: ['Frontend', 'UI'],
    logo: null,
  },
  Highcharts: {
    title: 'Highcharts',
    id: 'Highcharts',
    description: 'Библиотека для создания графиков и диаграмм',
    tags: ['Charts'],
    logo: null,
  },
  D3: {
    title: 'D3',
    id: 'D3',
    description: 'Функциональная библиотека для отображения данных',
    tags: ['Charts', 'FP'],
    logo: null,
  },
  Lodash: {
    title: 'Lodash',
    id: 'Lodash',
    description: 'Библиотека для функционального программирования',
    tags: ['FP'],
    logo: null,
  },
  Ramda: {
    title: 'Ramda',
    id: 'Ramda',
    description: 'Библиотека для функционального программирования',
    tags: ['FP'],
    logo: null,
  },
  Rxjs: {
    title: 'Rxjs',
    id: 'Rxjs',
    description: 'Библиотека для рективного программирования',
    tags: ['Reactive'],
    logo: null,
  },
  Effector: {
    title: 'Effector',
    id: 'Effector',
    description:
      'Стейт менеджер для упрощенной работы с бизнес логикой, основанный на событиях',
    tags: ['Reactive', 'StateManager', 'Frontend'],
    logo: null,
  },
  Gitlab: {
    title: 'Gitlab',
    id: 'Gitlab',
    description: 'Сервис для работы с репозиториями git с возможностью CI',
    tags: ['Devops'],
    logo: null,
  },
  RabbitMQ: {
    title: 'RabbitMQ',
    id: 'RabbitMQ',
    description: 'Брокер сообщений',
    tags: ['Devops', 'Backend'],
    logo: null,
  },
  'PG Admin': {
    title: 'PG Admin',
    id: 'PG Admin',
    description: 'Интерфейс для управления базой данных Postgresql',
    tags: ['Database', 'Backend'],
    logo: null,
  },

  Jest: {
    title: 'Jest',
    id: 'Jest',
    description: 'Библиотека для unit тестирования',
    tags: ['Testing'],
    logo: null,
  },
  'Testing library': {
    title: 'Testing library',
    id: 'Testing library',
    description: 'Библиотека для unit тестирования React-компонентов',
    tags: ['Testing', 'Frontend'],
    logo: null,
  },
  Playwright: {
    title: 'Playwright',
    id: 'Playwright',
    description: 'Система для end-to-end тестирования',
    tags: ['Testing', 'Frontend', 'Backend'],
    logo: null,
  },
  'UML diagrams': {
    title: 'UML diagrams',
    id: 'UML diagrams',
    description:
      'Используется для графического описания сущностей, запросов, процессов, интерфейсов и т.д.',
    tags: [],
    logo: null,
  },
};
