/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TechnologyWithTagsDto as DtoTechnologyWithTagsDto } from '../../models/dto/technology-with-tags-dto';
export interface AboutMeDto {
  bioParagraphs?: Array<string>;
  hobbies?: string;
  note?: string;
  technologies?: Array<DtoTechnologyWithTagsDto>;
}
