/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EducationDto {
  course?: string;
  id?: number;
  name?: string;
  organization?: string;
  year?: number;
}
