/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EducationDto as DtoEducationDto } from '../../models/dto/education-dto';
export interface EducationListResponse {
  content?: Array<DtoEducationDto>;
  page?: number;
  size?: number;
  total?: number;
}
