/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TagDto as DtoTagDto } from '../../models/dto/tag-dto';
export interface TagListResponse {
  content?: Array<DtoTagDto>;
  page?: number;
  size?: number;
  total?: number;
}
