/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TechnologyWithTagsDto as DtoTechnologyWithTagsDto } from '../../models/dto/technology-with-tags-dto';
export interface TechListResponse {
  content?: Array<DtoTechnologyWithTagsDto>;
  page?: number;
  size?: number;
  total?: number;
}
