/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TagDto as DtoTagDto } from '../../models/dto/tag-dto';
export interface TechnologyWithTagsDto {
  description?: string;
  id?: number;
  logoUrl?: string;
  tags?: Array<DtoTagDto>;
  title?: string;
}
