/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkHistoryDto {
  about?: string;
  id?: number;
  logoUrl?: string;
  name?: string;
  periodEnd?: string;
  periodStart?: string;
  projects?: Array<string>;
  whatIDid?: Array<string>;
}
