/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TechnologyWithTagsDto as DtoTechnologyWithTagsDto } from '../../models/dto/technology-with-tags-dto';
export interface WorkHistoryWithTechnologiesDto {
  about?: string;
  id?: number;
  jobTitle?: string;
  logoUrl?: string;
  name?: string;
  periodEnd?: string;
  periodStart?: string;
  projects?: Array<string>;
  technologies?: Array<DtoTechnologyWithTagsDto>;
  whatIDid?: Array<string>;
}
