/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkHistoryWithTechnologiesDto as DtoWorkHistoryWithTechnologiesDto } from '../../models/dto/work-history-with-technologies-dto';
export interface WorkHistoryListResponse {
  content?: Array<DtoWorkHistoryWithTechnologiesDto>;
  page?: number;
  size?: number;
  total?: number;
}
