/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EducationDto as DtoEducationDto } from '../../models/dto/education-dto';

export interface EduEduIdGet$Params {

/**
 * ID записи образования
 */
  eduID: number;
}

export function eduEduIdGet(http: HttpClient, rootUrl: string, params: EduEduIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DtoEducationDto>> {
  const rb = new RequestBuilder(rootUrl, eduEduIdGet.PATH, 'get');
  if (params) {
    rb.path('eduID', params.eduID, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DtoEducationDto>;
    })
  );
}

eduEduIdGet.PATH = '/edu/{eduID}';
