/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TagDto as DtoTagDto } from '../../models/dto/tag-dto';

export interface TagPut$Params {
  
    /**
     * Данные тега
     */
    body: {
} & {
'hexColor'?: string;
'id'?: number;
'name'?: string;
}
}

export function tagPut(http: HttpClient, rootUrl: string, params: TagPut$Params, context?: HttpContext): Observable<StrictHttpResponse<DtoTagDto>> {
  const rb = new RequestBuilder(rootUrl, tagPut.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DtoTagDto>;
    })
  );
}

tagPut.PATH = '/tag';
