/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TagDto as DtoTagDto } from '../../models/dto/tag-dto';

export interface TagTagIdGet$Params {

/**
 * ID тега
 */
  tagID: number;
}

export function tagTagIdGet(http: HttpClient, rootUrl: string, params: TagTagIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DtoTagDto>> {
  const rb = new RequestBuilder(rootUrl, tagTagIdGet.PATH, 'get');
  if (params) {
    rb.path('tagID', params.tagID, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DtoTagDto>;
    })
  );
}

tagTagIdGet.PATH = '/tag/{tagID}';
