/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkHistoryDto as DtoWorkHistoryDto } from '../../models/dto/work-history-dto';

export interface WhPut$Params {
  
    /**
     * Данные записи
     */
    body: {
} & {
'about'?: string;
'id'?: number;
'logoUrl'?: string;
'name'?: string;
'periodEnd'?: string;
'periodStart'?: string;
'projects'?: Array<string>;
'whatIDid'?: Array<string>;
}
}

export function whPut(http: HttpClient, rootUrl: string, params: WhPut$Params, context?: HttpContext): Observable<StrictHttpResponse<DtoWorkHistoryDto>> {
  const rb = new RequestBuilder(rootUrl, whPut.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DtoWorkHistoryDto>;
    })
  );
}

whPut.PATH = '/wh';
