/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkHistoryWithTechnologiesDto as DtoWorkHistoryWithTechnologiesDto } from '../../models/dto/work-history-with-technologies-dto';

export interface WhWhIdGet$Params {

/**
 * ID записи истории работы
 */
  whID: number;
}

export function whWhIdGet(http: HttpClient, rootUrl: string, params: WhWhIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DtoWorkHistoryWithTechnologiesDto>> {
  const rb = new RequestBuilder(rootUrl, whWhIdGet.PATH, 'get');
  if (params) {
    rb.path('whID', params.whID, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DtoWorkHistoryWithTechnologiesDto>;
    })
  );
}

whWhIdGet.PATH = '/wh/{whID}';
