/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HeroDto as DtoHeroDto } from '../../models/dto/hero-dto';

export interface HeroGet$Params {
}

export function heroGet(http: HttpClient, rootUrl: string, params?: HeroGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DtoHeroDto>> {
  const rb = new RequestBuilder(rootUrl, heroGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DtoHeroDto>;
    })
  );
}

heroGet.PATH = '/hero';
